services:
  - type: web
    name: shawnzyluxe
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SHOPIFY_DOMAIN
        sync: false
      - key: SHOPIFY_STOREFRONT_TOKEN
        sync: false
      - key: SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_ID
        sync: false
      - key: SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
