services:
  - type: web
    name: shawnzyluxe
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 -b 0.0.0.0:$PORT app:app
    healthCheckPath: /
    domains:
      - vantavcommerce.com
      - www.vantavcommerce.com
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SHOPIFY_DOMAIN
        sync: false
      - key: SHOPIFY_STOREFRONT_TOKEN
        sync: false
      - key: SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_ID
        sync: false
      - key: SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: MASTER_ADMIN_EMAIL
        value: shawn@vantavcommerce.com
      - key: RECAPTCHA_SITE_KEY
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: ENGINEER_EMAIL
        value: engineer@vantavcommerce.com
      - key: TEMP_ACCOUNTS_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SHOPIFY_WEBHOOK_SECRET
        sync: false
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_DOMAIN
        sync: false
      - key: MERCHANT_EMAIL
        sync: false
      - key: MERCHANT_PHONE
        sync: false
      - key: SUPPLIER_EMAIL
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: SHOPIFY_STORE_URL
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: SHOPIFY_CLIENT_ID
        sync: false
      - key: SHOPIFY_CLIENT_SECRET
        sync: false
      - key: OAUTH_REDIRECT_URI
        value: https://vantavcommerce.com
