services:
  - type: web
    name: shawnzyluxe
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SHOPIFY_DOMAIN
        sync: false
      - key: SHOPIFY_STOREFRONT_TOKEN
        sync: false
      - key: SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_ID
        sync: false
      - key: SHOPIFY_CUSTOMER_ACCOUNT_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: SHOPIFY_WEBHOOK_SECRET
        sync: false
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: MERCHANT_EMAIL
        sync: false
      - key: SUPPLIER_EMAIL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: SHOPIFY_STORE_URL
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: SHOPIFY_CLIENT_ID
        sync: false
      - key: SHOPIFY_CLIENT_SECRET
        sync: false
      - key: OAUTH_REDIRECT_URI
        value: https://shawnzyluxe.com
