# Shopify app configuration
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration
name = "Vantav"
client_id = "c29ad26cbdb891be3c4c96b567b7ccba"
application_url = "https://vantavcommerce.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
scopes = "read_products,write_products,read_orders,read_inventory,read_fulfillments"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://vantavcommerce.com/api/v1/auth/shopify/callback",
]

[webhooks]
api_version = "2025-04"

# Mandatory compliance webhooks for the Shopify App Store
[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "https://vantavcommerce.com/api/v1/webhooks/shopify-gdpr/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "https://vantavcommerce.com/api/v1/webhooks/shopify-gdpr/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "https://vantavcommerce.com/api/v1/webhooks/shopify-gdpr/shop/redact"

# App lifecycle webhook
[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://vantavcommerce.com/api/v1/webhooks/shopify/app/uninstalled"
